[package]
name = "watcher"
version = "0.1.0"
edition = "2024"
authors = ["Leanterm contributors"]
publish.workspace = true
license.workspace = true

[dependencies]
leanterm_errors.workspace = true
async-channel.workspace = true
leanterm_ui_core.workspace = true
log.workspace = true
anyhow.workspace = true
notify-debouncer-full.workspace = true
futures.workspace = true
