[package]
name = "ai"
version = "0.1.0"
edition = "2024"
publish.workspace = true
license.workspace = true

[features]
jemalloc = []
local_fs = []
test-util = []

[dependencies]
cfg-if.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
itertools.workspace = true
ignore = "0.4.23"
log.workspace = true
lazy_static.workspace = true
regex.workspace = true
strsim.workspace = true
derivative.workspace = true
chrono.workspace = true
persistence.workspace = true

[target.'cfg(unix)'.dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]

[dev-dependencies]

[build-dependencies]
anyhow.workspace = true
