use std::path::Path;

use super::*;

fn generated_worktree_path_string(repo: &str, worktree_name: &str) -> String {
    super::super::tab_config::generated_worktree_path(Path::new(repo), worktree_name)
        .display()
        .to_string()
}

// ── SessionType helpers ──




// ── build_tab_config ──







#[test]
fn directory_path_is_absolute_in_directory() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/absolute/path/here"),
        false,
        true,
    );

    let directory = config.panes[0].directory.as_deref().unwrap();
    assert!(
        directory.starts_with('/'),
        "directory should be absolute, got: {directory}"
    );
}

// ── TOML round-trip ──

#[test]
fn round_trip_terminal_no_worktree() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );
    let toml_str = toml::to_string_pretty(&config).expect("Should serialize");
    let parsed: TabConfig = toml::from_str(&toml_str).expect("Should deserialize");

    assert_eq!(parsed.name, config.name);
    assert_eq!(parsed.panes[0].directory, config.panes[0].directory);
    assert_eq!(parsed.panes[0].commands, config.panes[0].commands);
}


// ── render_tab_config integration ──

#[test]
fn render_terminal_produces_correct_pane_template() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );
    let param_values = config.default_param_values();
    let (title, pane_template) = super::super::render_tab_config(&config, &param_values, None);

    assert!(title.is_none());
    if let crate::launch_configs::launch_config::PaneTemplateType::PaneTemplate {
        cwd,
        commands,
        ..
    } = pane_template
    {
        assert_eq!(cwd, std::path::PathBuf::from("/home/user/project"));
        assert!(commands.is_empty());
    } else {
        panic!("Expected PaneTemplate variant");
    }
}



// ── write_tab_config (file naming) ──

#[test]
fn write_tab_config_creates_file_with_correct_naming() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );

    let path1 = write_tab_config(&config, dir.path(), "startup_config")
        .expect("First write should succeed");
    assert_eq!(path1.file_name().unwrap(), "startup_config.toml");

    let path2 = write_tab_config(&config, dir.path(), "startup_config")
        .expect("Second write should succeed");
    assert_eq!(path2.file_name().unwrap(), "startup_config_1.toml");

    let path3 = write_tab_config(&config, dir.path(), "startup_config")
        .expect("Third write should succeed");
    assert_eq!(path3.file_name().unwrap(), "startup_config_2.toml");
}


#[test]
fn write_tab_config_creates_directory_if_missing() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    let nested = dir.path().join("nested").join("tab_configs");
    let config = build_tab_config(&SessionType::Terminal, Path::new("/tmp"), false, true);

    let path = write_tab_config(&config, &nested, "startup_config").expect("Write should succeed");
    assert!(path.exists());
}

#[test]
fn write_tab_config_custom_base_name() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );

    let path =
        write_tab_config(&config, dir.path(), "my_tab_config").expect("Write should succeed");
    assert_eq!(path.file_name().unwrap(), "my_tab_config.toml");
}

#[test]
fn terminal_with_autogenerated_worktree() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/repo"),
        true,
        true,
    );

    assert!(config.title.is_none());
    let expected_worktree_path =
        generated_worktree_path_string("/home/user/repo", "{{autogenerated_branch_name}}");
    assert_eq!(
        config.panes[0].commands.as_deref().unwrap(),
        [
            format!(
                "git worktree add -b {{{{autogenerated_branch_name}}}} \"{expected_worktree_path}\""
            ),
            format!("cd \"{expected_worktree_path}\""),
        ]
        .as_ref()
    );
    assert!(config.uses_autogenerated_branch_name());
    assert!(config.params.is_empty());
}

// ── tab_config_from_pane_snapshot ──









// ── snapshot pane_type derivation ──







// ── nested / multi-level pane layout edge cases ──






// ── is_git_repo ──

#[test]
fn detects_git_repo_with_dot_git_dir() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    std::fs::create_dir(dir.path().join(".git")).expect("Should create .git dir");

    assert!(is_git_repo(dir.path()));
}



