[package]
authors = ["Leanterm contributors"]
edition = "2024"
name = "secret_redaction"
publish.workspace = true
license.workspace = true

[dependencies]
itertools.workspace = true
lazy_static.workspace = true
log.workspace = true
parking_lot.workspace = true
regex.workspace = true
regex-automata.workspace = true
regex_dfas.workspace = true
string-offset.workspace = true
leanterm_core.workspace = true
leanterm_errors.workspace = true
